- name: General Config
  hosts: routers
  gather_facts: yes
  connection: network_cli
  collections:
    - community.cisco.ios
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
  - name: Add Banner
    cisco.ios.ios_banner:
      banner: login
      text: |
        Authorized Personnel Only
      state: present

  - name: Add loopback
    cisco.ios.ios_interfaces:
      config:
      - name: Loopback21
        enabled: true

  - name: Assign IP address to Loopback21
    cisco.ios.ios_l3_interfaces:
        config:
          - name: Loopback21
            ipv4:
              - address: 192.168.31.1/32
              - address: 192.168.31.2/32
                secondary: true
        state: merged

  - name: Gather interface facts
    cisco.ios.ios_facts:
      gather_subset: interfaces

  - name: Show only Loopback21
    debug:
      msg: "{{ ansible_net_interfaces['Loopback21'] }}"

  - name: Run command on router
    cisco.ios.ios_command:
      commands:
          - show running-config | section Loopback21
    register: loopback_config

  - name: Print Loopback21 config
    debug:
        var: loopback_config.stdout[0]