---
- name: Install TextFSM and verify
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Install TextFSM
      ansible.builtin.pip:
        name: textfsm
        state: present

    # - name: Wait 5 minutes for verification
    #   ansible.builtin.pause:
    #     minutes: 5
    #     prompt: "TextFSM installed. Verify now and press Enter to continue or Ctrl+C to abort"

    - name: Verify TextFSM is installed
      ansible.builtin.command: python3 -c "import textfsm; print(textfsm.__version__)"
      register: textfsm_version

    - name: Print TextFSM version
      ansible.builtin.debug:
        msg: "TextFSM version installed: {{ textfsm_version.stdout }}"
